#!/bin/bash

set -ex

folder="/srv/conda/envs/notebook/share/jupyter/kernels/xcpp14"
mkdir -p $folder

cat > "$folder/kernel.json" << EOF
{
    "display_name": "MPI&C++14",
    "argv": [
        "/srv/conda/envs/notebook/bin/xcpp",
        "-f",
        "{connection_file}",
        "-std=c++14",
        "-I/srv/conda/envs/notebook/include",
        "-pthread",
        "-L/srv/conda/envs/notebook/lib",
        "-lmpi"
    ],
    "language": "C++14"
}
EOF
